apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-example-front-proxy
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: prod
  components:
    - name: auth-proxy
      src: auth-proxy
      publicPort: http
      secrets:
        - OAUTH2_PROXY_CLIENT_SECRET
        - OAUTH2_PROXY_COOKIE_SECRET
      ports:
        - name: http
          port: 8000
    - name: frontend
      src: frontend
      ports:
        - name: http
          port: 8001
    - name: api
      src: api
      ports:
        - name: http
          port: 8002
  dnsAppAlias:
    environment: prod
    component: auth-proxy
